// examples/react/basic/src/index.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { createTemplate } from '@tanstack/template'
import { useTemplate } from '@tanstack/react-template'

function App() {
  const template = React.useMemo(
    () => createTemplate({ message: 'Hello from React!' }),
    [],
  )
  const state = useTemplate(template)

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>TanStack Template - React Basic Example</h1>
      <p>Message: {state.message}</p>
      <button onClick={() => template.greet()}>Greet (check console)</button>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root')!).render(<App />)

// examples/solid/basic/src/index.tsx
import { render } from 'solid-js/web'
import { createTemplate } from '@tanstack/template'
import { createTemplateSignal } from '@tanstack/solid-template'

function App() {
  const template = createTemplate({ message: 'Hello from Solid!' })
  const state = createTemplateSignal(template)

  return (
    <div style={{ padding: '20px', 'font-family': 'sans-serif' }}>
      <h1>TanStack Template - Solid Basic Example</h1>
      <p>Message: {state().message}</p>
      <button onClick={() => template.greet()}>Greet (check console)</button>
    </div>
  )
}

render(() => <App />, document.getElementById('root')!)
